### PR TITLE
[#152966754] Feature: retries in Redis

### LINKED ISSUE #70: Current retry messages logic is conflicting with usage of prefetch_count setting
By its nature, RabbitMQ's `prefetch_count` setting limits the number of messages sent to a worker at a given time. To release consumed message and receive a new one, a worker should acknowledge consumed message first.

This conflicts with the implementation of "retry" logic. Because messages scheduled for a retry are delayed from being redelivered using JS's `setTimeout()`, workers acknowledge them only after the timeout.

Thus, when a worker is waiting on more retry messages than `prefetch_count` setting, a worker will receive no new messages.

Example: prefetch count 3, 5 messages scheduled for a retry, 32 new messages are not processed.
image

### LINKED ISSUE #154: Workers crash when they can't fit all messages in the queue to the memory
Blink wasn't designed with support for queues with lengthy backlogs.
Given the asynchronous nature of Node.js, workers are trying to consume all available messages from their queues. When queue backlog has more messages than possible to fit into the memory available to a worker, worker crashes.

image

This is important for two reasons:

- Longer backlogs are anticipated in Blink with rate limiter in place
- Expected backfill operations in most cases would generate queue backlogs longer than normal relay operations would do. For example, customer.io backfill on the screenshot above produced 70K messages in the queue and `customer-io-update-customer` couldn't fit all them into its memory.

### PR DESCRIPTION
**Pull request by sergii-tkachenko**
### What's this PR do?
This PR contains multiple major changes to Blink core.

#### Rate Limiter
- Default rate limiter is changed from 60 to 100
- Default rate limiter for Customer Io broadcast relay is set to 50
- Custom rate limits are available!

Documentation: https://github.com/DoSomething/blink/wiki/Rate-limiter

#### Retries
- Default backoff strategy changed back to `DelayLogic .exponentialBackoff()`
- Default retry limit changed from 18000 to 100
- New concept of `Delayer` introduced
- The old delayer  see (#70) moved to `InMemoryRetryDelayer` class
- New delayer `RedisRetryDelayer`. It's enabled by default now
- Now retries are dependent on new worker, called `redis-retries-republish`

Documentation: https://github.com/DoSomething/blink/wiki/Retries (Includes full flowchart)

#### Workers
- Workers don't have to implement `constructor()` anymore (you can if you want)
- Workers don't have bind `consume` method anymore, it's done automatically.
- Workers now must call `super.setup()` in their `setup()` method
- Workers now must call declare their queue through `super.setup()`

Documentation: https://github.com/DoSomething/blink/wiki/Workers

#### Messages
- Concrete message classes don't have to implement `fromCtx()` and `fromRabbitMessage()` methods anymore. Everything is done automatically through `Message` superclass

Documentation: https://github.com/DoSomething/blink/wiki/Messages

#### Queues
Documentation: https://github.com/DoSomething/blink/wiki/Queues

#### Timers
- New concept of `BlinkTimerApp` implemented
- New concept of `SkipTimer` implemented
- New concept of `TimerTask` implemented
- First `RedisRetriesRepublishTimerTask` is created

Documentation: https://github.com/DoSomething/blink/wiki/Timers

### How should this be manually tested?
- `yarn install`
- `docker-compose up`
- `yarn test:full`

### Any background context you want to provide?
This PR is low on unit tests, but it includes comprehensive integration test for the full message cycle. See `test/integration/timers/RedisRetriesRepublishTimerTask.test.js`.

### Deployment plan
1. Merge, release and deploy #181 (make it v2.0.0-beta.8) 
2. Click "Update branch" on this PR. THIS IS VITAL
3. Deploy this to staging. It already has Redis addon attached. All env variable are set
4. Manually test EVERY message. See logs for unexpected errors
5. Merge this PR
6. Bump the version to `v2.0.0`!!!! 🎉 
7. Ensure production environment variables are set correctly. Check `BLINK_REDIS_*` variables. I did set them all, just in case
8. Deploy!
9. Start `redis-retries-republish` worker, 1 dyno (never more, than one!)
10. Monitor `redis-retries-republish` memory for a couple of days
11. Add `blink_retries` Redis collection to daily checkup

### What are the relevant tickets?
Pivotal [152966754](https://www.pivotaltracker.com/story/show/152966754)
Fixes #70 
Fixes #154

### CODE REVIEW

File: src/app/BlinkApp.js [hunk 1]
```diff
@@ -84,6 +89,18 @@ class BlinkApp {
     return broker;
   }
 
+  async setupRedis() {
+    // Now only RabbitMQ is supported.
+    const redis = new RedisConnectionManager(this.config.redis);
+    // Establish connection or perform authorization.
+    const result = await redis.connect();
+    if (!result) {
+      // Do what?
```
Comment (rapala61) [inline src/app/BlinkApp.js]: Let's add a `//TODO` here to comeback to handle the trouble-path scenario.

File: src/timers/RedisRetriesRepublishTimerTask.js [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+
+    // Pressess each message.
+    packedMessages.forEach(async (packedMessage) => {
+      try {
+        await this.republishMessage(packedMessage);
+        await this.redisRetryDelayer.removeProcessedMessage(packedMessage);
+      } catch (error) {
+        this.log(
+          'error',
+          `Unepxected error during processing ${packedMessage}`,
```
Comment (rapala61) [inline src/timers/RedisRetriesRepublishTimerTask.js]: small typo
