### PR TITLE
removed unnecessary validations in CampaignSignupPost Message.

### LINKED ISSUE #125: Relay Rogue campaign_signup_post type to cio events to indicate kind of member action
## TL;DR

**Sergii Tkachenko:** So, to summarize: "classic" Phoenix report back _item_* will become `campaign_signup_post` with `type: "action"`. And, for example, DACA call will be the same `campaign_signup_post`, but with type: `"call"`.

**Shae Smith:** yea that's about right. How we end up actually defining/counting a "reportback" will probably change in the coming months, but that is the idea.

_* - Added per Shae's clarification_

## Long Slack chat version:

[10:21 AM] 
Sergii Tkachenko Hey Shae, good morning!

[10:21 AM] 
Do you have time for a quick chat about setting reportback event type to cio signup post events?

[10:23 AM] 
So the idea is to assume that now all signups posts are reportbacks

[10:24 AM] 
so we'll add a type attribute to event arguments and set it to reportback

[10:24 AM] 
however, real event type is still stay campaign_signup_post

[10:24 AM] 
example

[10:25 AM] 
Sergii Tkachenko uploaded this image: Pasted image at 2017-09-22, 10:25 AM
Add Comment

[10:25 AM] 
Sergii Tkachenko
activity type (see col 3) will stay the same

[10:25 AM] 
and I'll extend actual data attributes with `type: "reportback",`

[10:26 AM] 
do you think this could be issue with current Rogue events implementation?

[10:26 AM] 
Shae Smith I see, thank you for the explanation.

[10:26 AM] 
> So the idea is to assume that now all signups posts are reportbacks

[10:27 AM] 
This is what is a little confusing- We tried in Rogue, to not assume that every post is a reportback

[10:27 AM] 
In fact, as we look towards multi-action campaigns, we really don't want to assume everything is a reportback

[10:28 AM] 
a Rogue `Post` paralleles what a `ReportbackItem` was in Phoenix-Ashes

[10:28 AM] 
and we say that a user has a "Reportback" if they have at least one of them

[10:28 AM] 
So if a user has 5 posts under a signup, they still only have one reportback

[10:30 AM] 
If your event classification works for C.io, then that is great, but just want to be clear about how were are defining stuff so that you all can be on the same page before segmenting things.

[10:31 AM] 
And some forward thinking- We might be including Post types in the `Post` model so that we can determine if a Post ties to different actions on a campaign

[10:31 AM] 
but that is to come

[10:32 AM] 
Sergii Tkachenko Ah, I see. Would it be less confusing to set the typo to `reportback_item` instead?

[10:32 AM] 
> And some forward thinking- We might be including Post types in the `Post` model so that we can determine if a Post ties to different actions on a campaign

[10:32 AM] 
yes, that would be perfect solution

[10:32 AM] 
Shae Smith
I would rather us also get rid of the "Reportback" terminology

[10:32 AM] 
maybe `action_item`?

[10:33 AM] 
or just `action`

[10:33 AM] 
Sergii Tkachenko yes, sound great

[10:33 AM] 
I like `action`

[10:34 AM] 
More forward thinking: could you please think of few examples when signup post events are not `actions`?

[10:34 AM] 
Insta post?

[10:35 AM] 
To clarify: trying to think what different post types could be on Post `model`

[10:36 AM] 
Shae Smith
sure!

[10:36 AM] 
so for example. There is a DACA campaign, and each day we give users new actions to take

[10:37 AM] 
a campaign lead would add actions, could be tweets, call your senator, IG posts, etc

[10:37 AM] 
and we would ingest those actions (somehow lol) as `Posts` (we could rethink this terminolgy in Rogue)

[10:39 AM] 
So a Post object could look something like this

[10:46 AM] 
Sergii Tkachenko Great example! Thanks.

[10:47 AM] 
Shae Smith
sorry my computer is being weird

[10:47 AM] 
but the idea is we want to leave it open so that a campaign lead could give users multple things to do

[10:47 AM] 
 ```
{
    id: "1",
    signup_id: "5970",
    campaign_id: "1603",
    northstar_id: "laksjdlfjadslf", 
    url: "http://www.url.com", // could be a link to a playlist, youtube video, image
    status: "pending",
    source: "phoenix-web",
    remote_addr: ""
    action_bucket: 1 // Each day would be a new "bucket", One campaign could have multiple buckets and each bucket could have multiple actions we ask the user to do. 
    action_type: "call", // The actual type of action "tweet", "call", "IG",etc 
    action_completes: true, // If the action completes the bucket or not. 
}
```
(edited)

[10:48 AM] 
none of the teminolgy has been solidified, and I don't even know if all of this is going to happen

[10:48 AM] 
but that is the idea

[10:48 AM] 
But i think considering each post and "action" for now is safe

[10:49 AM] 
Sergii Tkachenko So to summarize: "classic" Phoenix report back will become `campaign_signup_post` with  `type: "action"`. And, for example, DACA call will be the same `campaign_signup_post`, but with `type: "call"`. (edited)

[10:49 AM] 
Sounds about right?

[10:51 AM] 
Shae Smith yea that's about right. How we end up actually defining/counting a "reportback" will probably change in the coming months, but that is the idea.

### LINKED ISSUE #173: Blink should not require a `campaign_run_id` in validation for a Rogue post
When sending a new post from Rogue, we were getting `422` errors from Blink when we did not send a `campaign_run_id` for a new post:
```
at=warning application=blink env=staging code=error_validation_failed request_id=8f9bf989-bca3-411c-a072-5b43e48c1380 method=POST host=blink-staging.dosomething.org path=/api/v1/events/user-signup-post fwd=54.159.163.56 protocol=https MessageValidationBlinkError: child "campaign_run_id" fails because ["campaign_run_id" is required], message {"data":{"id":392751,"signup_id":8084848,"quantity":"2","why_participated":"why participated","campaign_id":"8888","campaign_run_id":"","northstar_id":"5589c9bb469c6475138b81f0","url":"https://rogue-thor.dosomething.org/images/392751","caption":"first caption","status":"pending","remote_addr":"24.90.89.121","source":"rogue-oauth","created_at":"2017-12-08T17:21:30+00:00","updated_at":"2017-12-08T17:21:30+00:00","deleted_at":null},"meta":{"request_id":"8f9bf989-bca3-411c-a072-5b43e48c1380","retryAttempt":0}}
```
Phoenix-Next does not have `campaign_run_id`s so we should not require this. Full Slack thread [here](https://dosomething.slack.com/archives/C0YGXUE01/p1512753239000108).

### PR DESCRIPTION
**Pull request by rapala61**
#### Validations for the `/api/v1/events/user-signup-post` route

It validates only a minimum set of required properties that the messaging team is expecting for successful segmentation. All other properties sent, aside from this subset of required props, are considered optional or nullable. More on which are considered required vs optional: [Blink Validation section](https://github.com/orgs/DoSomething/teams/team-bleed/discussions/13).

## How to test
- Run the tests and get no errors:
    - `cd` into your local Blink repo.
    - `yarn install`
    - `docker-compose up -d`
    - `yarn test:full`
    - `docker-compose down`

## Relevant Issues
Fixes #125 
Fixes #173 
Removes the quantity requirement for this route mentioned in #174 
Fixes part 1 of the Validation tasks in [Pivotal #154736700](https://www.pivotaltracker.com/story/show/154736700)

## Other tasks
- [x] Deploy to staging.
- [x] Extensive (~ 2 people) report-back (Campaign Signup Posts) events test in **staging**. cc @aaronschachter @justkika @sbsmith86 (Team Bleed). Basically, just going through a reportback and inspecting the event generated for your **staging** user in the **staging** C.io instance.
- [x] Update [CampaignSignupPostMessage Schema](https://github.com/DoSomething/blink/wiki/Message-Schemas#campaignsignuppostmessage) Wiki docs.
- [x] Test `voter-reg` type of Signup Posts in **staging**

### CODE REVIEW

**Comment by aaronschachter** [comment]
This looks like it closes #173 too!

File: test/helpers/MessageFactoryHelper.js [hunk 1]
```diff
@@ -162,40 +162,36 @@ class MessageFactoryHelper {
...
-      'why_participated',
-      'url',
-    ];
-    optionalFields.forEach((key) => {
-      if (chance.bool({ likelihood: 40 })) {
-        delete data[key];
-      }
-    });
+      // Optional / nullable
+      campaign_run_id: chance.pickone([null, 99, 'abc99']),
```
Comment (aaronschachter) [inline test/helpers/MessageFactoryHelper.js]: Unless something's changed I think `campaign_run_id` would always be an integer. Should this logic be moved to the `campaign_id` ? We currently are passing integers as Campaign ID's but aim to pass strings eventually for Phoenix Next.

File: test/helpers/MessageFactoryHelper.js [hunk 2]
```diff
@@ -162,40 +162,36 @@ class MessageFactoryHelper {
...
+      source: chance.pickone([null, 'campaigns', 'phoenix-web']),
+      media: chance.pickone([null, {
+        url: chance.avatar({ protocol: 'https' }),
+        caption: chance.sentence({ words: 5 }),
+      }]),
+      why_participated: chance.pickone([null, chance.sentence()]),
+      updatead_at: chance.pickone([null, updatedAt]),
```
Comment (aaronschachter) [inline test/helpers/MessageFactoryHelper.js]: Spelling ⌨️

File: src/messages/CampaignSignupPostMessage.js [hunk 3]
```diff
@@ -1,71 +1,62 @@
...
 
-    // Optional fields.
-    const optionalFields = [
-      'source',
-      'caption',
-      'url',
-      'why_participated',
-    ];
+    /**
+     * { cioKey: dataKey } Mappings
```
Comment (aaronschachter) [inline src/messages/CampaignSignupPostMessage.js]: Should this be { dataKey: cioKey }? The `signup_post_id` property should map to the Customer io `id` ? I was having a little trouble following the logic with `cioKeys` but it seems it's to set what field we should be using for `id`.

File: test/helpers/MessageFactoryHelper.js [hunk 4]
```diff
@@ -162,40 +162,36 @@ class MessageFactoryHelper {
   static getValidCampaignSignupPost() {
     const createdAt = chance.date({ year: (new Date()).getFullYear() }).toISOString();
     const updatedAt = moment(createdAt).add(1, 'days').toISOString();
+    const deletedAt = moment(createdAt).add(2, 'days').toISOString();
 
     const data = {
-      // Required
+      // Required minimunm
```
Comment (aaronschachter) [inline test/helpers/MessageFactoryHelper.js]: Spelling Police 🐕 🚓

**Comment by aaronschachter** [comment]
Verified I see the Post event in Customer.io:
```
{
action: "default"
campaign_id: "1524"
campaign_run_id: "6242"
caption: "jasdfja"
created_at: 1518201447
northstar_id: "5547be89469c64ec7d8b518d"
quantity: 0
remote_addr: "172.19.74.106"
signup_id: "8496868"
signup_post_id: "433205"
source: "sms"
status: "pending"
type: "photo"
updated_at: "2018-02-09T18:37:27+00:00"
url: https://rogue-thor.dosomething.org/images/433205
version: 3
why_participated: "jememealkj"
}
```

File: test/helpers/MessageFactoryHelper.js (hunk 1 above)
Comment (rapala61) [reply test/helpers/MessageFactoryHelper.js]: Hmm... that makes sense. We require it, but we don't validate that is a String or a Number, as long as it's not empty its fine. We so cast it to String before sending to C.io so that is consistent with what's coming next. I'll update the tests to reflect that. Thank you!

Comment (rapala61) [reply test/helpers/MessageFactoryHelper.js]: Actually, I got confused a little confused there: `campaign_id` is being validated to be a String. Based on the [Post Model section](https://github.com/orgs/DoSomething/teams/team-bleed/discussions/13), the `campaign_id` is a VARCHAR. This is why Blink receives it as a String and why we validate against a String type value.

File: src/messages/CampaignSignupPostMessage.js (hunk 3 above)
Comment (rapala61) [reply src/messages/CampaignSignupPostMessage.js]: > The `signup_post_id` property should map to the Customer io `id` ?

Backwards, the Rogue data object's `id` property, maps to the C.io's `signup_post_id`. The final event posted to C.io contains a `signup_post_id` instead of the original `id` property.

Comment (rapala61) [reply src/messages/CampaignSignupPostMessage.js]: Added  [better comments](https://github.com/DoSomething/blink/pull/191/files#diff-0b4cc4e6d17137117a832bc587e83dd9R40)
